### ISSUE TITLE
Exception when running Invoke-IcingaCheckUsedPartitionSpace

### ISSUE THREAD

**Issue by Laszlo-Fiat** [Icinga/icinga-powershell-plugins#130]
I have a server with a dynamic disk that spans across multiple drives. Executing:
PS C:\Windows\system32> Invoke-IcingaCheckUsedPartitionSpace -Warning 80 -Critical 90
Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'D'  Key being added: 'D
'"
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Icinga_ProviderDisks.psm1:75 cha
r:9
+         $PartitionDiskByDriveLetter.Add(
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

The output returned after the exception seems to be correct, but Icinga2 sees the exception, and I get the Unknown status.

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.
Is there anything missing for the output? do you miss a disc for example?

I'm just wondering on why the plugin tries to add the same drive again.

**Comment by Laszlo-Fiat** [comment]
Hello,
Nothing is missing from the output. 
See the picture, the problematic d: drive is on dynamic disks, and spanning over two disks.  
Thank you for looking into this.
![image](https://user-images.githubusercontent.com/13178935/108890361-c6fc2d80-760d-11eb-8ef0-95b240722265.png)

**Comment by LordHepipud** [comment]
Thank you for the input! That explains why the drive is being added multiple times.
I'm just curios on how to resolve this. The base data (disk size for example) seems to be different from one disk to another.

The easiest way would be to simply check if the drive letter was already added and skip in that case. How ever, this is pretty sure not the correct way as in my oppinion we should check both disk states.

Am I missing something?

**Comment by Laszlo-Fiat** [comment]
I'd recommend to simply check if the drive letter was already added and skip in that case. We only have visibility on the drive level, we cannot tell how much the utilization is on Disk 1 or Disk 4 part of Drive D:.

**Comment by LordHepipud** [comment]
Could you please check with the current master if this issue is fixed? We re-designed the entire plugin with #71 

Thank you in advance!

**Comment by LordHepipud** [comment]
This should be fixed now, if not - please re-open the issue

**Comment by Laszlo-Fiat** [comment]
Hello, I've upgraded to 1.7.0 from 1.3.1, and I hope the upgrade really happened, but I still have this issue:

icinga> Invoke-IcingaCheckUsedPartitionSpace -Warning 90 -Critical 95
Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'D'  Key being added: 'D
'"
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Icinga_ProviderDisks.psm1:75 cha
r:9
+         $PartitionDiskByDriveLetter.Add(
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

[OK] Used Partition Space
| 'partition_m'=23.32848%;90;95;0;100 'partition_l'=8.55253%;90;95;0;100 'partition_d'=86.88597%;90;95;0;100 'partition_
f'=65.90682%;90;95;0;100 'partition_i'=41.40739%;90;95;0;100 'used_space_partition_f'=1244833000000B;1.699899;1.794338;0
;1888777000000 'used_space_partition_j'=1162467000000B;1.316220;1.389344;0;1462467000000 'used_space_partition_e'=141103
1000000B;1.781669;1.880651;0;1979632000000 'used_space_partition_m'=933081800000B;3.599779;3.799766;0;3999754000000 'use
d_space_partition_d'=2773307000000B;2.872703;3.032298;0;3191893000000 'used_space_partition_c'=107507400000B;176.744531;
186.563672;0;196382800000 'used_space_partition_i'=782043800000B;1.699792;1.794225;0;1888658000000 'used_space_partition
_l'=769693600000B;8.099641;8.549621;0;8999602000000 'partition_c'=54.74378%;90;95;0;100 'partition_j'=79.48669%;90;95;0;
100 'partition_e'=71.2774%;90;95;0;100
0

**Comment by LordHepipud** [comment]
This seems to be still the old version. The partition plugin is no longer using the `Icinga_ProviderDisks.psm1` provider.

**Comment by Laszlo-Fiat** [comment]
How can I check if I use an old version?  I updated from 1.3.1 to 1.7 by running the newest install script to upgrade the framework, then I ran update-icinga to upgrade everything else. Now, if I run update-icinga, I get this:

PS C:\Windows\system32> use-icinga
PS C:\Windows\system32> update-icinga
[Notice]: No update package found for component "agent"
[Notice]: No update package found for component "plugins"
[Notice]: No update package found for component "framework"

**Comment by LordHepipud** [comment]
Okay, that seems to be fine. Can you please run

```powershell
icinga { Invoke-IcingaCheckUsedPartitionSpace -Warning 80% -Critical 90% } -RebuildCache
```

Does it work afterwards or do you still receive the same error? Can you please share the output of

```powershell
Show-Icinga
```

This will give a summary of the current installation
