### ISSUE TITLE
Path not found when pathname contains brackets

### ISSUE THREAD

**Issue by jschroedertrianel** [Icinga/icinga-powershell-plugins#401]
I'm trying to check a directory which contains brackets in the pathname, for example:

c:\temp\test [1]\

I tried several ways of escaping the brackets in the path configuration but nothing seems to work. I always receive 

Icinga Invalid Input Error was thrown: Invalid Input Exception: Path not found
Invalid Input exception occured:
Plugin execution failed because the defined -Path does not exist on this system

**Comment by LordHepipud** [comment]
Thank you for the issue. I assume the problem in this case is that the brackets will be handled as regular expression.
I will have a look on that.

**Comment by LordHepipud** [comment]
Could you please try and test the linked PR? this should resolve the issue.

**Comment by jschroedertrianel** [comment]
Thank you for your help. I tested the provided fix but sadly I still receive the error:

Icinga Invalid Input Error was thrown: Invalid Input Exception: Path not found
Invalid Input exception occured:
Plugin execution failed because the defined -Path does not exist on this system

**Comment by LordHepipud** [comment]
Have you rebuild the cache after you made those changes?

```powershell
icinga -RebuildCache { Restart-IcingaForWindows; };
```

This should actually resolve the issue.
